import { IEventListItem } from "Interfaces/IEventList";
import { ICategories } from "Interfaces/ICategory";
import { korbook } from "stories/Containers/7-AllCategoryMenuSub.stories";

export const mainEventList: IEventListItem[] = [
  {
    id: "a1",
    displayName: "요즘 이 책",
    list: [
      {
        id: "bnV_a02",
        displayName: "bnV_a02",
        href: "/",
        src: "bnV_a02.jpg",
        color: "#E2F3D3",
      },
    ],
  },
  {
    id: "a2",
    displayName: "핫이슈",
    list: [
      {
        id: "bnN_w01",
        displayName: "bnN_w01",
        href: "/",
        src: "bnN_w01.jpg",
        color: "#CCE3FF",
      },
      {
        id: "bnN_w02",
        displayName: "bnN_w02",
        href: "/",
        src: "bnN_w02.jpg",
        color: "#E0F2FC",
      },
      {
        id: "bnN_w03",
        displayName: "bnN_w03",
        href: "/",
        src: "bnN_w03.jpg",
        color: "#EDD3D4",
      },
      {
        id: "bnN_w04",
        displayName: "bnN_w04",
        href: "/",
        src: "bnN_w04.jpg",
        color: "#F1F1F1",
      },
      {
        id: "bnN_w05",
        displayName: "bnN_w05",
        href: "/",
        src: "bnN_w05.jpg",
        color: "#FDDCBB",
      },
      {
        id: "bnN_w06",
        displayName: "bnN_w06",
        href: "/",
        src: "bnN_w06.jpg",
        color: "#F7F2EC",
      },
      {
        id: "bnN_w07",
        displayName: "bnN_w07",
        href: "/",
        src: "bnN_w07.jpg",
        color: "#FFEAC1",
      },
      {
        id: "bnN_w08",
        displayName: "bnN_w08",
        href: "/",
        src: "bnN_w08.jpg",
        color: "#FFECCB",
      },
    ],
  },
  {
    id: "a3",
    displayName: "새로나온책",
    list: [
      {
        id: "bnV_a01",
        displayName: "bnV_a01",
        href: "/",
        src: "bnV_a01.jpg",
        color: "#E2F3D3",
      },
      {
        id: "bnV_a02",
        displayName: "bnV_a02",
        href: "/",
        src: "bnV_a02.jpg",
        color: "#E2F3D3",
      },
    ],
  },
  {
    id: "a4",
    displayName: "기획/테마",
    list: [
      {
        id: "bnN_w08",
        displayName: "bnN_w08",
        href: "/",
        src: "bnN_w08.jpg",
        color: "#FFECCB",
      },
    ],
  },
  {
    id: "a5",
    displayName: "ebook",
    list: [
      {
        id: "bnC_we01",
        displayName: "bnC_we01",
        href: "/",
        src: "bnC_we01.jpg",
        color: "#F8F4D7",
      },
      {
        id: "bnC_we02",
        displayName: "bnC_we02",
        href: "/",
        src: "bnC_we02.jpg",
        color: "#F8F4D7",
      },
      {
        id: "bnC_we03",
        displayName: "bnC_we03",
        href: "/",
        src: "bnC_we03.jpg",
        color: "#F8F4D7",
      },
      {
        id: "bnC_we04",
        displayName: "bnC_we04",
        href: "/",
        src: "bnC_we04.jpg",
        color: "#F8F4D7",
      },
      {
        id: "bnC_we05",
        displayName: "bnC_we05",
        href: "/",
        src: "bnC_we05.jpg",
        color: "#F8F4D7",
      },
      {
        id: "bnC_we06",
        displayName: "bnC_we06",
        href: "/",
        src: "bnC_we06.jpg",
        color: "#F8F4D7",
      },
    ],
  },
  {
    id: "a6",
    displayName: "sam",
    list: [
      {
        id: "bnC_we04",
        displayName: "bnC_we04",
        href: "/",
        src: "bnC_we04.jpg",
        color: "#F8F4D7",
      },
    ],
  },
  {
    id: "a7",
    displayName: "한정특가",
    list: [
      {
        id: "bnC_we06",
        displayName: "bnC_we06",
        href: "/",
        src: "bnC_we06.jpg",
        color: "#F8F4D7",
      },
    ],
  },
];
export const bookCategories: ICategories[] = [
  {
    id: "korbook",
    list: [
      { categoryIndex: "1", id: "daa", displayName: "소설" },
      { categoryIndex: "1", id: "dab", displayName: "시/에세이" },
      { categoryIndex: "1", id: "dag", displayName: "경제/경영" },
      { categoryIndex: "1", id: "dah", displayName: "자기계발" },
      { categoryIndex: "2", id: "dac", displayName: "인문" },
      { categoryIndex: "2", id: "dad", displayName: "역사/문화" },
      { categoryIndex: "2", id: "dae", displayName: "종교" },
      { categoryIndex: "2", id: "daf", displayName: "정치/사회" },
      { categoryIndex: "2", id: "dap", displayName: "예술/대중문화" },
      { categoryIndex: "2", id: "daz", displayName: "과학" },
      { categoryIndex: "2", id: "da1", displayName: "기술/공학" },
      { categoryIndex: "2", id: "da2", displayName: "컴퓨터/IT" },
      { categoryIndex: "3", id: "dai", displayName: "유아(0~7세)" },
      { categoryIndex: "3", id: "daj", displayName: "어린이(초등)" },
      { categoryIndex: "3", id: "dal", displayName: "어린이전집" },
      { categoryIndex: "3", id: "dak", displayName: "어린이영어" },
      { categoryIndex: "3", id: "dao", displayName: "청소년" },
      { categoryIndex: "4", id: "dam", displayName: "초등참고서" },
      { categoryIndex: "4", id: "dan", displayName: "중/고등참고서" },
      { categoryIndex: "4", id: "da5", displayName: "대학교재" },
      { categoryIndex: "4", id: "da8", displayName: "방송통신대교재" },
      { categoryIndex: "4", id: "da3", displayName: "취업/수험서" },
      { categoryIndex: "4", id: "dax", displayName: "외국어" },
      { categoryIndex: "5", id: "das", displayName: "가정/육아" },
      { categoryIndex: "5", id: "dav", displayName: "건강" },
      { categoryIndex: "5", id: "daq", displayName: "여행" },
      { categoryIndex: "5", id: "dat", displayName: "요리" },
      { categoryIndex: "5", id: "dar", displayName: "취미/실용/스포츠" },
      { categoryIndex: "6", id: "dau", displayName: "잡지" },
      { categoryIndex: "6", id: "daw", displayName: "만화" },
      { categoryIndex: "7", id: "da6", displayName: "한국소개도서" },
    ],
  },
  {
    id: "otherbook",
    list: [
      { categoryIndex: "1", id: "c35", displayName: "영미도서" },
      { categoryIndex: "1", id: "xaa", displayName: "문학" },
      { categoryIndex: "1", id: "xae", displayName: "인문/사회" },
      { categoryIndex: "1", id: "xaf", displayName: "경제/경영" },
      { categoryIndex: "1", id: "xag", displayName: "과학/기술" },
      { categoryIndex: "1", id: "xab", displayName: "취미/실용/여행" },
      { categoryIndex: "1", id: "xai", displayName: "ELT/어학/사전" },
      { categoryIndex: "1", id: "xaj", displayName: "교재" },
      { categoryIndex: "1", id: "xac", displayName: "생활/요리/건강" },
      { categoryIndex: "1", id: "xad", displayName: "예술/건축" },
      { categoryIndex: "2", id: "xah", displayName: "어린이영어" },
      { categoryIndex: "2", id: "c37", displayName: "유아영어" },
      { categoryIndex: "2", id: "c38", displayName: "영역별영어학습" },
      { categoryIndex: "2", id: "c39", displayName: "코스북" },
      { categoryIndex: "2", id: "c3b", displayName: "영어동화/그림책" },
      { categoryIndex: "2", id: "c3a", displayName: "미국교과서" },
      { categoryIndex: "2", id: "c3c", displayName: "어린이중국어" },
      { categoryIndex: "2", id: "c3d", displayName: "어린이일본어" },
      { categoryIndex: "3", id: "c36", displayName: "일본도서" },
      { categoryIndex: "3", id: "rDq", displayName: "잡지" },
      { categoryIndex: "3", id: "rDv", displayName: "실용서/예술" },
      { categoryIndex: "3", id: "rDp", displayName: "만화/애니" },
      { categoryIndex: "3", id: "rDx", displayName: "문학" },
      { categoryIndex: "3", id: "rDt", displayName: "문고" },
      { categoryIndex: "3", id: "rDy", displayName: "라이트노벨" },
      { categoryIndex: "3", id: "rDr", displayName: "어학/학습" },
      { categoryIndex: "3", id: "rDs", displayName: "엔터테인먼트" },
      { categoryIndex: "3", id: "rDa", displayName: "아동" },
      { categoryIndex: "3", id: "rDw", displayName: "인문/사회" },
      { categoryIndex: "3", id: "rDz", displayName: "자연/기술과학" },
      { categoryIndex: "3", id: "rDu", displayName: "신서" },
      // {categoryIndex: '1',        id:"c67",   displayName: "베스트셀러" },
      // {categoryIndex: '1',        id:"c68",   displayName: "새로나온책" },
      // {categoryIndex: '1',        id:"c6a",   displayName: "일본신간잡지" },
      // {categoryIndex: '1',        id:"XXA",   displayName: "일본잡지 정기구독" },
      // {categoryIndex: '1',        id:"rqe",   displayName: "이벤트 마당" },
    ],
  },
];
export const bookKorbookEvents: IEventListItem[] = [
  {
    id: "1",
    displayName: "어린이/학습",
    list: [
      {
        id: "s20",
        displayName: "상반기유아동 Top100",
        href: "/",
        src: "bnL_01.jpg",
      },
      {
        id: "s21",
        displayName: "유아어린이 세트 1위는?",
        href: "/",
        src: "bnL_02.jpg",
      },
      {
        id: "s22",
        displayName: "총 300만원 상당의경품",
        href: "/",
        src: "bnF_01.jpg",
      },
      {
        id: "s23",
        displayName: "흔한남매 X 하루한장",
        href: "/",
        src: "bnYY_22.jpg",
      },
    ],
  },
  {
    id: "1",

    displayName: "문학/실용",
    list: [
      {
        id: "s30",
        displayName: "교보문고x그린 블리스",
        href: "/",
        src: "bnE_01.jpg",
      },
      {
        id: "s31",
        displayName: "스타작가 100 대 1",
        href: "/",
        src: "bnC_01.jpg",
      },
      {
        id: "s32",
        displayName: "에세이 1위, 스프링노트",
        href: "/",
        src: "bnN_01.jpg",
      },
      {
        id: "s33",
        displayName: "쌍갑포차 이벤트",
        href: "/",
        src: "bnC_02.jpg",
      },
    ],
  },
  {
    id: "1",

    displayName: "인문/교양",
    list: [
      {
        id: "s40",
        displayName: "인문교양 읽는 맛",
        href: "/",
        src: "bnG_01.jpg",
      },
      {
        id: "s41",
        displayName: "뇌과학, 통찰과 질문",
        href: "/",
        src: "bnF_02.jpg",
      },
      {
        id: "s42",
        displayName: "실크로드X데스크매트",
        href: "/",
        src: "bnN_02.jpg",
      },
      {
        id: "s43",
        displayName: "백상 젊은연극상 모티브",
        href: "/",
        src: "bnA_01.jpg",
      },
    ],
  },
  {
    id: "1",

    displayName: "비즈/수험",
    list: [
      {
        id: "s50",
        displayName: "인플루엔셜 단독 브랜드전",
        href: "/",
        src: "bnV_01.jpg",
      },
      {
        id: "s51",
        displayName: "한빛미디어 단독 브랜드전",
        href: "/",
        src: "bnG_02.jpg",
      },
      {
        id: "s52",
        displayName: "파고다 브랜드전",
        href: "/",
        src: "bnN_03.jpg",
      },
      {
        id: "s53",
        displayName: "교보단독 선택증정",
        href: "/",
        src: "bnL_03.jpg",
      },
    ],
  },
];
